### ISSUE TITLE
Tutorials and articles have several broken links

### ISSUE THREAD

**Issue by raymundovr** [wapc/wapc.io#330]
Hi,

I've noticed that all links in the section "Tutorials and Articles" are currently broken as the vino.dev website is now redirecting to a different site that does not contain the mentioned tutorials.

Any chance to get them back somehow?
Thanks

**Comment by pkedy** [comment]
Thanks for reporting this! We are in the process of updating the website and will fix it then.

**Comment by pkedy** [comment]
The site was updated. Thanks again!
